### ISSUE TITLE
No "high" scores for some schools

### ISSUE THREAD

**Issue by jordantomax** [AdmitHub/college-chooser#2]
which is breaking conditionals
![screenshot 2015-04-17 11 54 21](https://cloud.githubusercontent.com/assets/37018/7205778/bec7d354-e4f9-11e4-9a5f-58b782e53b1e.png)

**Comment by yourcelf** [comment]
This is a source data problem.  @AndrewMagliozzi and Kirk need to decide how they'd like this to show up on the UI.  About half the schools are missing one of GPA/SAT or ACT, so we need a UI strategy that responds to that.  We aren't going to be able to get that data easily.

**Comment by AndrewMagliozzi** [comment]
We are working on it now.  There are also some issues in the data we have.
We'll discuss Monday.

**Comment by jordantomax** [comment]
Great, thanks guys
