### ISSUE TITLE
Allow inputs within ftb to have classes specific to their data

### ISSUE THREAD

**Issue by jordantomax** [AdmitHub/college-chooser#3]
This would be useful for fields like phone, which should be naturally shorter than other fields. 

Also, do we have the capability to add placeholders to the inputs?

**Comment by yourcelf** [comment]
For either, just add the property to the "autoform" option:

        fields: [
          {
            field: "name",
            options: {
              optional: false,
              autoform: {
                placeholder: "I'm a placeholder",
                "class": "ui-awesome",
                prompt: "What is your name?",
                help: "Your name as you'd put it on a college application."
              }
            }
          },

Best to wrap the word "class" in double-quotes, since it's a reserved word in ES6 (the next version of javascript).
